platform: linux

resources:
- name: gorez
  type: git
  source:
    uri: https://github.com/goehmen/gorez.git
    branch: master


image_resource:
  type: docker-image
    source: {repository: ubuntu}

#inputs:
#- name: gorez
#
#run:
# path: ./flight-school/ci/test.sh

