---
resource_types:
- name: cf-goehmen
 type: docker-image
 source:
   repository: concourse/cf-resource

- name: twitter
  type: docker-image
  source:
    repository: ecsteam/twitter-concourse-resource

resources:
- name: resource-gorez-app
  type: git
  source:
    uri: https://github.com/goehmen/gorez.git

- name: tweet-source
  type: git
  source:
    uri: https://github.com/goehmen/gorez.git

- name: tweet
  type: twitter
  source:
    consumer_key: {{twitter-consumer-key}}
    consumer_secret: {{twitter-consumer-secret}}
    access_token: {{twitter-access-token}}
    access_token_secret: {{twitter-access-token-secret}}

- name: resource-deploy-gorez-app
  type: cf-goehmen
#  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: true

jobs:
- name: job-deploy-app
  serial: true
  plan:
  - {get: resource-gorez-app, trigger: true}
  - put: resource-deploy-gorez-app
    params:
      manifest: resource-gorez-app/manifest.yml
      path: resource-gorez-app

- name: do-tweet
  plan:
  - get: tweet-source
    passed: [job-deploy-app]
  - put: tweet
    params:
      media:
      - tweet-source/images/GreenBuild.png
      status: >
        POW!!! Concourse deployed my app! (build ${BUILD_ID})
        @concourseci FTW 
